// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: amazon_ups.proto

#ifndef PROTOBUF_amazon_5fups_2eproto__INCLUDED
#define PROTOBUF_amazon_5fups_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3002000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3002000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
class AUCommands;
class AUCommandsDefaultTypeInternal;
extern AUCommandsDefaultTypeInternal _AUCommands_default_instance_;
class ConnectWorld;
class ConnectWorldDefaultTypeInternal;
extern ConnectWorldDefaultTypeInternal _ConnectWorld_default_instance_;
class ConnectedWorld;
class ConnectedWorldDefaultTypeInternal;
extern ConnectedWorldDefaultTypeInternal _ConnectedWorld_default_instance_;
class Deliver;
class DeliverDefaultTypeInternal;
extern DeliverDefaultTypeInternal _Deliver_default_instance_;
class Delivered;
class DeliveredDefaultTypeInternal;
extern DeliveredDefaultTypeInternal _Delivered_default_instance_;
class Load;
class LoadDefaultTypeInternal;
extern LoadDefaultTypeInternal _Load_default_instance_;
class Order;
class OrderDefaultTypeInternal;
extern OrderDefaultTypeInternal _Order_default_instance_;
class Truck;
class TruckDefaultTypeInternal;
extern TruckDefaultTypeInternal _Truck_default_instance_;
class UACommands;
class UACommandsDefaultTypeInternal;
extern UACommandsDefaultTypeInternal _UACommands_default_instance_;

namespace protobuf_amazon_5fups_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_amazon_5fups_2eproto

// ===================================================================

class Order : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Order) */ {
 public:
  Order();
  virtual ~Order();

  Order(const Order& from);

  inline Order& operator=(const Order& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Order& default_instance();

  static inline const Order* internal_default_instance() {
    return reinterpret_cast<const Order*>(
               &_Order_default_instance_);
  }

  void Swap(Order* other);

  // implements Message ----------------------------------------------

  inline Order* New() const PROTOBUF_FINAL { return New(NULL); }

  Order* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Order& from);
  void MergeFrom(const Order& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Order* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 whid = 1;
  bool has_whid() const;
  void clear_whid();
  static const int kWhidFieldNumber = 1;
  ::google::protobuf::int32 whid() const;
  void set_whid(::google::protobuf::int32 value);

  // required int32 x = 2;
  bool has_x() const;
  void clear_x();
  static const int kXFieldNumber = 2;
  ::google::protobuf::int32 x() const;
  void set_x(::google::protobuf::int32 value);

  // required int64 packageid = 4;
  bool has_packageid() const;
  void clear_packageid();
  static const int kPackageidFieldNumber = 4;
  ::google::protobuf::int64 packageid() const;
  void set_packageid(::google::protobuf::int64 value);

  // required int64 seqnum = 5;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 5;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // required int32 y = 3;
  bool has_y() const;
  void clear_y();
  static const int kYFieldNumber = 3;
  ::google::protobuf::int32 y() const;
  void set_y(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Order)
 private:
  void set_has_whid();
  void clear_has_whid();
  void set_has_x();
  void clear_has_x();
  void set_has_y();
  void clear_has_y();
  void set_has_packageid();
  void clear_has_packageid();
  void set_has_seqnum();
  void clear_has_seqnum();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 whid_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int64 packageid_;
  ::google::protobuf::int64 seqnum_;
  ::google::protobuf::int32 y_;
  friend struct  protobuf_amazon_5fups_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Load : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Load) */ {
 public:
  Load();
  virtual ~Load();

  Load(const Load& from);

  inline Load& operator=(const Load& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Load& default_instance();

  static inline const Load* internal_default_instance() {
    return reinterpret_cast<const Load*>(
               &_Load_default_instance_);
  }

  void Swap(Load* other);

  // implements Message ----------------------------------------------

  inline Load* New() const PROTOBUF_FINAL { return New(NULL); }

  Load* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Load& from);
  void MergeFrom(const Load& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Load* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 packageid = 2;
  bool has_packageid() const;
  void clear_packageid();
  static const int kPackageidFieldNumber = 2;
  ::google::protobuf::int64 packageid() const;
  void set_packageid(::google::protobuf::int64 value);

  // required int64 seqnum = 3;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 3;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // required bool isloading = 1;
  bool has_isloading() const;
  void clear_isloading();
  static const int kIsloadingFieldNumber = 1;
  bool isloading() const;
  void set_isloading(bool value);

  // @@protoc_insertion_point(class_scope:Load)
 private:
  void set_has_isloading();
  void clear_has_isloading();
  void set_has_packageid();
  void clear_has_packageid();
  void set_has_seqnum();
  void clear_has_seqnum();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int64 packageid_;
  ::google::protobuf::int64 seqnum_;
  bool isloading_;
  friend struct  protobuf_amazon_5fups_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Deliver : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Deliver) */ {
 public:
  Deliver();
  virtual ~Deliver();

  Deliver(const Deliver& from);

  inline Deliver& operator=(const Deliver& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Deliver& default_instance();

  static inline const Deliver* internal_default_instance() {
    return reinterpret_cast<const Deliver*>(
               &_Deliver_default_instance_);
  }

  void Swap(Deliver* other);

  // implements Message ----------------------------------------------

  inline Deliver* New() const PROTOBUF_FINAL { return New(NULL); }

  Deliver* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Deliver& from);
  void MergeFrom(const Deliver& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Deliver* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 packageid = 1;
  bool has_packageid() const;
  void clear_packageid();
  static const int kPackageidFieldNumber = 1;
  ::google::protobuf::int64 packageid() const;
  void set_packageid(::google::protobuf::int64 value);

  // required int64 seqnum = 2;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 2;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Deliver)
 private:
  void set_has_packageid();
  void clear_has_packageid();
  void set_has_seqnum();
  void clear_has_seqnum();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int64 packageid_;
  ::google::protobuf::int64 seqnum_;
  friend struct  protobuf_amazon_5fups_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ConnectedWorld : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ConnectedWorld) */ {
 public:
  ConnectedWorld();
  virtual ~ConnectedWorld();

  ConnectedWorld(const ConnectedWorld& from);

  inline ConnectedWorld& operator=(const ConnectedWorld& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ConnectedWorld& default_instance();

  static inline const ConnectedWorld* internal_default_instance() {
    return reinterpret_cast<const ConnectedWorld*>(
               &_ConnectedWorld_default_instance_);
  }

  void Swap(ConnectedWorld* other);

  // implements Message ----------------------------------------------

  inline ConnectedWorld* New() const PROTOBUF_FINAL { return New(NULL); }

  ConnectedWorld* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ConnectedWorld& from);
  void MergeFrom(const ConnectedWorld& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ConnectedWorld* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 seqnum = 2;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 2;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // required bool isconnected = 1;
  bool has_isconnected() const;
  void clear_isconnected();
  static const int kIsconnectedFieldNumber = 1;
  bool isconnected() const;
  void set_isconnected(bool value);

  // @@protoc_insertion_point(class_scope:ConnectedWorld)
 private:
  void set_has_isconnected();
  void clear_has_isconnected();
  void set_has_seqnum();
  void clear_has_seqnum();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int64 seqnum_;
  bool isconnected_;
  friend struct  protobuf_amazon_5fups_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class AUCommands : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:AUCommands) */ {
 public:
  AUCommands();
  virtual ~AUCommands();

  AUCommands(const AUCommands& from);

  inline AUCommands& operator=(const AUCommands& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const AUCommands& default_instance();

  static inline const AUCommands* internal_default_instance() {
    return reinterpret_cast<const AUCommands*>(
               &_AUCommands_default_instance_);
  }

  void Swap(AUCommands* other);

  // implements Message ----------------------------------------------

  inline AUCommands* New() const PROTOBUF_FINAL { return New(NULL); }

  AUCommands* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const AUCommands& from);
  void MergeFrom(const AUCommands& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(AUCommands* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .Order order = 2;
  int order_size() const;
  void clear_order();
  static const int kOrderFieldNumber = 2;
  const ::Order& order(int index) const;
  ::Order* mutable_order(int index);
  ::Order* add_order();
  ::google::protobuf::RepeatedPtrField< ::Order >*
      mutable_order();
  const ::google::protobuf::RepeatedPtrField< ::Order >&
      order() const;

  // repeated .Load loading = 3;
  int loading_size() const;
  void clear_loading();
  static const int kLoadingFieldNumber = 3;
  const ::Load& loading(int index) const;
  ::Load* mutable_loading(int index);
  ::Load* add_loading();
  ::google::protobuf::RepeatedPtrField< ::Load >*
      mutable_loading();
  const ::google::protobuf::RepeatedPtrField< ::Load >&
      loading() const;

  // repeated .Deliver todeliver = 4;
  int todeliver_size() const;
  void clear_todeliver();
  static const int kTodeliverFieldNumber = 4;
  const ::Deliver& todeliver(int index) const;
  ::Deliver* mutable_todeliver(int index);
  ::Deliver* add_todeliver();
  ::google::protobuf::RepeatedPtrField< ::Deliver >*
      mutable_todeliver();
  const ::google::protobuf::RepeatedPtrField< ::Deliver >&
      todeliver() const;

  // repeated int64 acks = 5;
  int acks_size() const;
  void clear_acks();
  static const int kAcksFieldNumber = 5;
  ::google::protobuf::int64 acks(int index) const;
  void set_acks(int index, ::google::protobuf::int64 value);
  void add_acks(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      acks() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_acks();

  // optional .ConnectedWorld connected = 1;
  bool has_connected() const;
  void clear_connected();
  static const int kConnectedFieldNumber = 1;
  const ::ConnectedWorld& connected() const;
  ::ConnectedWorld* mutable_connected();
  ::ConnectedWorld* release_connected();
  void set_allocated_connected(::ConnectedWorld* connected);

  // @@protoc_insertion_point(class_scope:AUCommands)
 private:
  void set_has_connected();
  void clear_has_connected();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::Order > order_;
  ::google::protobuf::RepeatedPtrField< ::Load > loading_;
  ::google::protobuf::RepeatedPtrField< ::Deliver > todeliver_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > acks_;
  ::ConnectedWorld* connected_;
  friend struct  protobuf_amazon_5fups_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Truck : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Truck) */ {
 public:
  Truck();
  virtual ~Truck();

  Truck(const Truck& from);

  inline Truck& operator=(const Truck& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Truck& default_instance();

  static inline const Truck* internal_default_instance() {
    return reinterpret_cast<const Truck*>(
               &_Truck_default_instance_);
  }

  void Swap(Truck* other);

  // implements Message ----------------------------------------------

  inline Truck* New() const PROTOBUF_FINAL { return New(NULL); }

  Truck* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Truck& from);
  void MergeFrom(const Truck& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Truck* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 whnum = 1;
  bool has_whnum() const;
  void clear_whnum();
  static const int kWhnumFieldNumber = 1;
  ::google::protobuf::int32 whnum() const;
  void set_whnum(::google::protobuf::int32 value);

  // required int32 truckid = 2;
  bool has_truckid() const;
  void clear_truckid();
  static const int kTruckidFieldNumber = 2;
  ::google::protobuf::int32 truckid() const;
  void set_truckid(::google::protobuf::int32 value);

  // required int64 packageid = 3;
  bool has_packageid() const;
  void clear_packageid();
  static const int kPackageidFieldNumber = 3;
  ::google::protobuf::int64 packageid() const;
  void set_packageid(::google::protobuf::int64 value);

  // required int64 seqnum = 4;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 4;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Truck)
 private:
  void set_has_whnum();
  void clear_has_whnum();
  void set_has_truckid();
  void clear_has_truckid();
  void set_has_packageid();
  void clear_has_packageid();
  void set_has_seqnum();
  void clear_has_seqnum();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int32 whnum_;
  ::google::protobuf::int32 truckid_;
  ::google::protobuf::int64 packageid_;
  ::google::protobuf::int64 seqnum_;
  friend struct  protobuf_amazon_5fups_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ConnectWorld : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ConnectWorld) */ {
 public:
  ConnectWorld();
  virtual ~ConnectWorld();

  ConnectWorld(const ConnectWorld& from);

  inline ConnectWorld& operator=(const ConnectWorld& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ConnectWorld& default_instance();

  static inline const ConnectWorld* internal_default_instance() {
    return reinterpret_cast<const ConnectWorld*>(
               &_ConnectWorld_default_instance_);
  }

  void Swap(ConnectWorld* other);

  // implements Message ----------------------------------------------

  inline ConnectWorld* New() const PROTOBUF_FINAL { return New(NULL); }

  ConnectWorld* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const ConnectWorld& from);
  void MergeFrom(const ConnectWorld& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(ConnectWorld* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 worldid = 1;
  bool has_worldid() const;
  void clear_worldid();
  static const int kWorldidFieldNumber = 1;
  ::google::protobuf::int64 worldid() const;
  void set_worldid(::google::protobuf::int64 value);

  // required int64 seqnum = 2;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 2;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:ConnectWorld)
 private:
  void set_has_worldid();
  void clear_has_worldid();
  void set_has_seqnum();
  void clear_has_seqnum();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int64 worldid_;
  ::google::protobuf::int64 seqnum_;
  friend struct  protobuf_amazon_5fups_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Delivered : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Delivered) */ {
 public:
  Delivered();
  virtual ~Delivered();

  Delivered(const Delivered& from);

  inline Delivered& operator=(const Delivered& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Delivered& default_instance();

  static inline const Delivered* internal_default_instance() {
    return reinterpret_cast<const Delivered*>(
               &_Delivered_default_instance_);
  }

  void Swap(Delivered* other);

  // implements Message ----------------------------------------------

  inline Delivered* New() const PROTOBUF_FINAL { return New(NULL); }

  Delivered* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Delivered& from);
  void MergeFrom(const Delivered& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Delivered* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int64 packageid = 1;
  bool has_packageid() const;
  void clear_packageid();
  static const int kPackageidFieldNumber = 1;
  ::google::protobuf::int64 packageid() const;
  void set_packageid(::google::protobuf::int64 value);

  // required int64 seqnum = 2;
  bool has_seqnum() const;
  void clear_seqnum();
  static const int kSeqnumFieldNumber = 2;
  ::google::protobuf::int64 seqnum() const;
  void set_seqnum(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:Delivered)
 private:
  void set_has_packageid();
  void clear_has_packageid();
  void set_has_seqnum();
  void clear_has_seqnum();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int64 packageid_;
  ::google::protobuf::int64 seqnum_;
  friend struct  protobuf_amazon_5fups_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class UACommands : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:UACommands) */ {
 public:
  UACommands();
  virtual ~UACommands();

  UACommands(const UACommands& from);

  inline UACommands& operator=(const UACommands& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const UACommands& default_instance();

  static inline const UACommands* internal_default_instance() {
    return reinterpret_cast<const UACommands*>(
               &_UACommands_default_instance_);
  }

  void Swap(UACommands* other);

  // implements Message ----------------------------------------------

  inline UACommands* New() const PROTOBUF_FINAL { return New(NULL); }

  UACommands* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UACommands& from);
  void MergeFrom(const UACommands& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output)
      const PROTOBUF_FINAL {
    return InternalSerializeWithCachedSizesToArray(
        ::google::protobuf::io::CodedOutputStream::IsDefaultSerializationDeterministic(), output);
  }
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UACommands* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ConnectWorld toconnect = 1;
  int toconnect_size() const;
  void clear_toconnect();
  static const int kToconnectFieldNumber = 1;
  const ::ConnectWorld& toconnect(int index) const;
  ::ConnectWorld* mutable_toconnect(int index);
  ::ConnectWorld* add_toconnect();
  ::google::protobuf::RepeatedPtrField< ::ConnectWorld >*
      mutable_toconnect();
  const ::google::protobuf::RepeatedPtrField< ::ConnectWorld >&
      toconnect() const;

  // repeated .Truck arrived = 2;
  int arrived_size() const;
  void clear_arrived();
  static const int kArrivedFieldNumber = 2;
  const ::Truck& arrived(int index) const;
  ::Truck* mutable_arrived(int index);
  ::Truck* add_arrived();
  ::google::protobuf::RepeatedPtrField< ::Truck >*
      mutable_arrived();
  const ::google::protobuf::RepeatedPtrField< ::Truck >&
      arrived() const;

  // repeated .Delivered finish = 3;
  int finish_size() const;
  void clear_finish();
  static const int kFinishFieldNumber = 3;
  const ::Delivered& finish(int index) const;
  ::Delivered* mutable_finish(int index);
  ::Delivered* add_finish();
  ::google::protobuf::RepeatedPtrField< ::Delivered >*
      mutable_finish();
  const ::google::protobuf::RepeatedPtrField< ::Delivered >&
      finish() const;

  // repeated int64 acks = 4;
  int acks_size() const;
  void clear_acks();
  static const int kAcksFieldNumber = 4;
  ::google::protobuf::int64 acks(int index) const;
  void set_acks(int index, ::google::protobuf::int64 value);
  void add_acks(::google::protobuf::int64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
      acks() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
      mutable_acks();

  // @@protoc_insertion_point(class_scope:UACommands)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::ConnectWorld > toconnect_;
  ::google::protobuf::RepeatedPtrField< ::Truck > arrived_;
  ::google::protobuf::RepeatedPtrField< ::Delivered > finish_;
  ::google::protobuf::RepeatedField< ::google::protobuf::int64 > acks_;
  friend struct  protobuf_amazon_5fups_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Order

// required int32 whid = 1;
inline bool Order::has_whid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Order::set_has_whid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Order::clear_has_whid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Order::clear_whid() {
  whid_ = 0;
  clear_has_whid();
}
inline ::google::protobuf::int32 Order::whid() const {
  // @@protoc_insertion_point(field_get:Order.whid)
  return whid_;
}
inline void Order::set_whid(::google::protobuf::int32 value) {
  set_has_whid();
  whid_ = value;
  // @@protoc_insertion_point(field_set:Order.whid)
}

// required int32 x = 2;
inline bool Order::has_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Order::set_has_x() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Order::clear_has_x() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Order::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline ::google::protobuf::int32 Order::x() const {
  // @@protoc_insertion_point(field_get:Order.x)
  return x_;
}
inline void Order::set_x(::google::protobuf::int32 value) {
  set_has_x();
  x_ = value;
  // @@protoc_insertion_point(field_set:Order.x)
}

// required int32 y = 3;
inline bool Order::has_y() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Order::set_has_y() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Order::clear_has_y() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Order::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline ::google::protobuf::int32 Order::y() const {
  // @@protoc_insertion_point(field_get:Order.y)
  return y_;
}
inline void Order::set_y(::google::protobuf::int32 value) {
  set_has_y();
  y_ = value;
  // @@protoc_insertion_point(field_set:Order.y)
}

// required int64 packageid = 4;
inline bool Order::has_packageid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Order::set_has_packageid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Order::clear_has_packageid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Order::clear_packageid() {
  packageid_ = GOOGLE_LONGLONG(0);
  clear_has_packageid();
}
inline ::google::protobuf::int64 Order::packageid() const {
  // @@protoc_insertion_point(field_get:Order.packageid)
  return packageid_;
}
inline void Order::set_packageid(::google::protobuf::int64 value) {
  set_has_packageid();
  packageid_ = value;
  // @@protoc_insertion_point(field_set:Order.packageid)
}

// required int64 seqnum = 5;
inline bool Order::has_seqnum() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Order::set_has_seqnum() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Order::clear_has_seqnum() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Order::clear_seqnum() {
  seqnum_ = GOOGLE_LONGLONG(0);
  clear_has_seqnum();
}
inline ::google::protobuf::int64 Order::seqnum() const {
  // @@protoc_insertion_point(field_get:Order.seqnum)
  return seqnum_;
}
inline void Order::set_seqnum(::google::protobuf::int64 value) {
  set_has_seqnum();
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:Order.seqnum)
}

// -------------------------------------------------------------------

// Load

// required bool isloading = 1;
inline bool Load::has_isloading() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Load::set_has_isloading() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Load::clear_has_isloading() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Load::clear_isloading() {
  isloading_ = false;
  clear_has_isloading();
}
inline bool Load::isloading() const {
  // @@protoc_insertion_point(field_get:Load.isloading)
  return isloading_;
}
inline void Load::set_isloading(bool value) {
  set_has_isloading();
  isloading_ = value;
  // @@protoc_insertion_point(field_set:Load.isloading)
}

// required int64 packageid = 2;
inline bool Load::has_packageid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Load::set_has_packageid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Load::clear_has_packageid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Load::clear_packageid() {
  packageid_ = GOOGLE_LONGLONG(0);
  clear_has_packageid();
}
inline ::google::protobuf::int64 Load::packageid() const {
  // @@protoc_insertion_point(field_get:Load.packageid)
  return packageid_;
}
inline void Load::set_packageid(::google::protobuf::int64 value) {
  set_has_packageid();
  packageid_ = value;
  // @@protoc_insertion_point(field_set:Load.packageid)
}

// required int64 seqnum = 3;
inline bool Load::has_seqnum() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Load::set_has_seqnum() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Load::clear_has_seqnum() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Load::clear_seqnum() {
  seqnum_ = GOOGLE_LONGLONG(0);
  clear_has_seqnum();
}
inline ::google::protobuf::int64 Load::seqnum() const {
  // @@protoc_insertion_point(field_get:Load.seqnum)
  return seqnum_;
}
inline void Load::set_seqnum(::google::protobuf::int64 value) {
  set_has_seqnum();
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:Load.seqnum)
}

// -------------------------------------------------------------------

// Deliver

// required int64 packageid = 1;
inline bool Deliver::has_packageid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Deliver::set_has_packageid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Deliver::clear_has_packageid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Deliver::clear_packageid() {
  packageid_ = GOOGLE_LONGLONG(0);
  clear_has_packageid();
}
inline ::google::protobuf::int64 Deliver::packageid() const {
  // @@protoc_insertion_point(field_get:Deliver.packageid)
  return packageid_;
}
inline void Deliver::set_packageid(::google::protobuf::int64 value) {
  set_has_packageid();
  packageid_ = value;
  // @@protoc_insertion_point(field_set:Deliver.packageid)
}

// required int64 seqnum = 2;
inline bool Deliver::has_seqnum() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Deliver::set_has_seqnum() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Deliver::clear_has_seqnum() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Deliver::clear_seqnum() {
  seqnum_ = GOOGLE_LONGLONG(0);
  clear_has_seqnum();
}
inline ::google::protobuf::int64 Deliver::seqnum() const {
  // @@protoc_insertion_point(field_get:Deliver.seqnum)
  return seqnum_;
}
inline void Deliver::set_seqnum(::google::protobuf::int64 value) {
  set_has_seqnum();
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:Deliver.seqnum)
}

// -------------------------------------------------------------------

// ConnectedWorld

// required bool isconnected = 1;
inline bool ConnectedWorld::has_isconnected() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ConnectedWorld::set_has_isconnected() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ConnectedWorld::clear_has_isconnected() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ConnectedWorld::clear_isconnected() {
  isconnected_ = false;
  clear_has_isconnected();
}
inline bool ConnectedWorld::isconnected() const {
  // @@protoc_insertion_point(field_get:ConnectedWorld.isconnected)
  return isconnected_;
}
inline void ConnectedWorld::set_isconnected(bool value) {
  set_has_isconnected();
  isconnected_ = value;
  // @@protoc_insertion_point(field_set:ConnectedWorld.isconnected)
}

// required int64 seqnum = 2;
inline bool ConnectedWorld::has_seqnum() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ConnectedWorld::set_has_seqnum() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ConnectedWorld::clear_has_seqnum() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ConnectedWorld::clear_seqnum() {
  seqnum_ = GOOGLE_LONGLONG(0);
  clear_has_seqnum();
}
inline ::google::protobuf::int64 ConnectedWorld::seqnum() const {
  // @@protoc_insertion_point(field_get:ConnectedWorld.seqnum)
  return seqnum_;
}
inline void ConnectedWorld::set_seqnum(::google::protobuf::int64 value) {
  set_has_seqnum();
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:ConnectedWorld.seqnum)
}

// -------------------------------------------------------------------

// AUCommands

// optional .ConnectedWorld connected = 1;
inline bool AUCommands::has_connected() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void AUCommands::set_has_connected() {
  _has_bits_[0] |= 0x00000001u;
}
inline void AUCommands::clear_has_connected() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void AUCommands::clear_connected() {
  if (connected_ != NULL) connected_->::ConnectedWorld::Clear();
  clear_has_connected();
}
inline const ::ConnectedWorld& AUCommands::connected() const {
  // @@protoc_insertion_point(field_get:AUCommands.connected)
  return connected_ != NULL ? *connected_
                         : *::ConnectedWorld::internal_default_instance();
}
inline ::ConnectedWorld* AUCommands::mutable_connected() {
  set_has_connected();
  if (connected_ == NULL) {
    connected_ = new ::ConnectedWorld;
  }
  // @@protoc_insertion_point(field_mutable:AUCommands.connected)
  return connected_;
}
inline ::ConnectedWorld* AUCommands::release_connected() {
  // @@protoc_insertion_point(field_release:AUCommands.connected)
  clear_has_connected();
  ::ConnectedWorld* temp = connected_;
  connected_ = NULL;
  return temp;
}
inline void AUCommands::set_allocated_connected(::ConnectedWorld* connected) {
  delete connected_;
  connected_ = connected;
  if (connected) {
    set_has_connected();
  } else {
    clear_has_connected();
  }
  // @@protoc_insertion_point(field_set_allocated:AUCommands.connected)
}

// repeated .Order order = 2;
inline int AUCommands::order_size() const {
  return order_.size();
}
inline void AUCommands::clear_order() {
  order_.Clear();
}
inline const ::Order& AUCommands::order(int index) const {
  // @@protoc_insertion_point(field_get:AUCommands.order)
  return order_.Get(index);
}
inline ::Order* AUCommands::mutable_order(int index) {
  // @@protoc_insertion_point(field_mutable:AUCommands.order)
  return order_.Mutable(index);
}
inline ::Order* AUCommands::add_order() {
  // @@protoc_insertion_point(field_add:AUCommands.order)
  return order_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Order >*
AUCommands::mutable_order() {
  // @@protoc_insertion_point(field_mutable_list:AUCommands.order)
  return &order_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Order >&
AUCommands::order() const {
  // @@protoc_insertion_point(field_list:AUCommands.order)
  return order_;
}

// repeated .Load loading = 3;
inline int AUCommands::loading_size() const {
  return loading_.size();
}
inline void AUCommands::clear_loading() {
  loading_.Clear();
}
inline const ::Load& AUCommands::loading(int index) const {
  // @@protoc_insertion_point(field_get:AUCommands.loading)
  return loading_.Get(index);
}
inline ::Load* AUCommands::mutable_loading(int index) {
  // @@protoc_insertion_point(field_mutable:AUCommands.loading)
  return loading_.Mutable(index);
}
inline ::Load* AUCommands::add_loading() {
  // @@protoc_insertion_point(field_add:AUCommands.loading)
  return loading_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Load >*
AUCommands::mutable_loading() {
  // @@protoc_insertion_point(field_mutable_list:AUCommands.loading)
  return &loading_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Load >&
AUCommands::loading() const {
  // @@protoc_insertion_point(field_list:AUCommands.loading)
  return loading_;
}

// repeated .Deliver todeliver = 4;
inline int AUCommands::todeliver_size() const {
  return todeliver_.size();
}
inline void AUCommands::clear_todeliver() {
  todeliver_.Clear();
}
inline const ::Deliver& AUCommands::todeliver(int index) const {
  // @@protoc_insertion_point(field_get:AUCommands.todeliver)
  return todeliver_.Get(index);
}
inline ::Deliver* AUCommands::mutable_todeliver(int index) {
  // @@protoc_insertion_point(field_mutable:AUCommands.todeliver)
  return todeliver_.Mutable(index);
}
inline ::Deliver* AUCommands::add_todeliver() {
  // @@protoc_insertion_point(field_add:AUCommands.todeliver)
  return todeliver_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Deliver >*
AUCommands::mutable_todeliver() {
  // @@protoc_insertion_point(field_mutable_list:AUCommands.todeliver)
  return &todeliver_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Deliver >&
AUCommands::todeliver() const {
  // @@protoc_insertion_point(field_list:AUCommands.todeliver)
  return todeliver_;
}

// repeated int64 acks = 5;
inline int AUCommands::acks_size() const {
  return acks_.size();
}
inline void AUCommands::clear_acks() {
  acks_.Clear();
}
inline ::google::protobuf::int64 AUCommands::acks(int index) const {
  // @@protoc_insertion_point(field_get:AUCommands.acks)
  return acks_.Get(index);
}
inline void AUCommands::set_acks(int index, ::google::protobuf::int64 value) {
  acks_.Set(index, value);
  // @@protoc_insertion_point(field_set:AUCommands.acks)
}
inline void AUCommands::add_acks(::google::protobuf::int64 value) {
  acks_.Add(value);
  // @@protoc_insertion_point(field_add:AUCommands.acks)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
AUCommands::acks() const {
  // @@protoc_insertion_point(field_list:AUCommands.acks)
  return acks_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
AUCommands::mutable_acks() {
  // @@protoc_insertion_point(field_mutable_list:AUCommands.acks)
  return &acks_;
}

// -------------------------------------------------------------------

// Truck

// required int32 whnum = 1;
inline bool Truck::has_whnum() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Truck::set_has_whnum() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Truck::clear_has_whnum() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Truck::clear_whnum() {
  whnum_ = 0;
  clear_has_whnum();
}
inline ::google::protobuf::int32 Truck::whnum() const {
  // @@protoc_insertion_point(field_get:Truck.whnum)
  return whnum_;
}
inline void Truck::set_whnum(::google::protobuf::int32 value) {
  set_has_whnum();
  whnum_ = value;
  // @@protoc_insertion_point(field_set:Truck.whnum)
}

// required int32 truckid = 2;
inline bool Truck::has_truckid() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Truck::set_has_truckid() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Truck::clear_has_truckid() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Truck::clear_truckid() {
  truckid_ = 0;
  clear_has_truckid();
}
inline ::google::protobuf::int32 Truck::truckid() const {
  // @@protoc_insertion_point(field_get:Truck.truckid)
  return truckid_;
}
inline void Truck::set_truckid(::google::protobuf::int32 value) {
  set_has_truckid();
  truckid_ = value;
  // @@protoc_insertion_point(field_set:Truck.truckid)
}

// required int64 packageid = 3;
inline bool Truck::has_packageid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Truck::set_has_packageid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Truck::clear_has_packageid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Truck::clear_packageid() {
  packageid_ = GOOGLE_LONGLONG(0);
  clear_has_packageid();
}
inline ::google::protobuf::int64 Truck::packageid() const {
  // @@protoc_insertion_point(field_get:Truck.packageid)
  return packageid_;
}
inline void Truck::set_packageid(::google::protobuf::int64 value) {
  set_has_packageid();
  packageid_ = value;
  // @@protoc_insertion_point(field_set:Truck.packageid)
}

// required int64 seqnum = 4;
inline bool Truck::has_seqnum() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Truck::set_has_seqnum() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Truck::clear_has_seqnum() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Truck::clear_seqnum() {
  seqnum_ = GOOGLE_LONGLONG(0);
  clear_has_seqnum();
}
inline ::google::protobuf::int64 Truck::seqnum() const {
  // @@protoc_insertion_point(field_get:Truck.seqnum)
  return seqnum_;
}
inline void Truck::set_seqnum(::google::protobuf::int64 value) {
  set_has_seqnum();
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:Truck.seqnum)
}

// -------------------------------------------------------------------

// ConnectWorld

// required int64 worldid = 1;
inline bool ConnectWorld::has_worldid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ConnectWorld::set_has_worldid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ConnectWorld::clear_has_worldid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ConnectWorld::clear_worldid() {
  worldid_ = GOOGLE_LONGLONG(0);
  clear_has_worldid();
}
inline ::google::protobuf::int64 ConnectWorld::worldid() const {
  // @@protoc_insertion_point(field_get:ConnectWorld.worldid)
  return worldid_;
}
inline void ConnectWorld::set_worldid(::google::protobuf::int64 value) {
  set_has_worldid();
  worldid_ = value;
  // @@protoc_insertion_point(field_set:ConnectWorld.worldid)
}

// required int64 seqnum = 2;
inline bool ConnectWorld::has_seqnum() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ConnectWorld::set_has_seqnum() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ConnectWorld::clear_has_seqnum() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ConnectWorld::clear_seqnum() {
  seqnum_ = GOOGLE_LONGLONG(0);
  clear_has_seqnum();
}
inline ::google::protobuf::int64 ConnectWorld::seqnum() const {
  // @@protoc_insertion_point(field_get:ConnectWorld.seqnum)
  return seqnum_;
}
inline void ConnectWorld::set_seqnum(::google::protobuf::int64 value) {
  set_has_seqnum();
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:ConnectWorld.seqnum)
}

// -------------------------------------------------------------------

// Delivered

// required int64 packageid = 1;
inline bool Delivered::has_packageid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Delivered::set_has_packageid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Delivered::clear_has_packageid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Delivered::clear_packageid() {
  packageid_ = GOOGLE_LONGLONG(0);
  clear_has_packageid();
}
inline ::google::protobuf::int64 Delivered::packageid() const {
  // @@protoc_insertion_point(field_get:Delivered.packageid)
  return packageid_;
}
inline void Delivered::set_packageid(::google::protobuf::int64 value) {
  set_has_packageid();
  packageid_ = value;
  // @@protoc_insertion_point(field_set:Delivered.packageid)
}

// required int64 seqnum = 2;
inline bool Delivered::has_seqnum() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Delivered::set_has_seqnum() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Delivered::clear_has_seqnum() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Delivered::clear_seqnum() {
  seqnum_ = GOOGLE_LONGLONG(0);
  clear_has_seqnum();
}
inline ::google::protobuf::int64 Delivered::seqnum() const {
  // @@protoc_insertion_point(field_get:Delivered.seqnum)
  return seqnum_;
}
inline void Delivered::set_seqnum(::google::protobuf::int64 value) {
  set_has_seqnum();
  seqnum_ = value;
  // @@protoc_insertion_point(field_set:Delivered.seqnum)
}

// -------------------------------------------------------------------

// UACommands

// repeated .ConnectWorld toconnect = 1;
inline int UACommands::toconnect_size() const {
  return toconnect_.size();
}
inline void UACommands::clear_toconnect() {
  toconnect_.Clear();
}
inline const ::ConnectWorld& UACommands::toconnect(int index) const {
  // @@protoc_insertion_point(field_get:UACommands.toconnect)
  return toconnect_.Get(index);
}
inline ::ConnectWorld* UACommands::mutable_toconnect(int index) {
  // @@protoc_insertion_point(field_mutable:UACommands.toconnect)
  return toconnect_.Mutable(index);
}
inline ::ConnectWorld* UACommands::add_toconnect() {
  // @@protoc_insertion_point(field_add:UACommands.toconnect)
  return toconnect_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::ConnectWorld >*
UACommands::mutable_toconnect() {
  // @@protoc_insertion_point(field_mutable_list:UACommands.toconnect)
  return &toconnect_;
}
inline const ::google::protobuf::RepeatedPtrField< ::ConnectWorld >&
UACommands::toconnect() const {
  // @@protoc_insertion_point(field_list:UACommands.toconnect)
  return toconnect_;
}

// repeated .Truck arrived = 2;
inline int UACommands::arrived_size() const {
  return arrived_.size();
}
inline void UACommands::clear_arrived() {
  arrived_.Clear();
}
inline const ::Truck& UACommands::arrived(int index) const {
  // @@protoc_insertion_point(field_get:UACommands.arrived)
  return arrived_.Get(index);
}
inline ::Truck* UACommands::mutable_arrived(int index) {
  // @@protoc_insertion_point(field_mutable:UACommands.arrived)
  return arrived_.Mutable(index);
}
inline ::Truck* UACommands::add_arrived() {
  // @@protoc_insertion_point(field_add:UACommands.arrived)
  return arrived_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Truck >*
UACommands::mutable_arrived() {
  // @@protoc_insertion_point(field_mutable_list:UACommands.arrived)
  return &arrived_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Truck >&
UACommands::arrived() const {
  // @@protoc_insertion_point(field_list:UACommands.arrived)
  return arrived_;
}

// repeated .Delivered finish = 3;
inline int UACommands::finish_size() const {
  return finish_.size();
}
inline void UACommands::clear_finish() {
  finish_.Clear();
}
inline const ::Delivered& UACommands::finish(int index) const {
  // @@protoc_insertion_point(field_get:UACommands.finish)
  return finish_.Get(index);
}
inline ::Delivered* UACommands::mutable_finish(int index) {
  // @@protoc_insertion_point(field_mutable:UACommands.finish)
  return finish_.Mutable(index);
}
inline ::Delivered* UACommands::add_finish() {
  // @@protoc_insertion_point(field_add:UACommands.finish)
  return finish_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::Delivered >*
UACommands::mutable_finish() {
  // @@protoc_insertion_point(field_mutable_list:UACommands.finish)
  return &finish_;
}
inline const ::google::protobuf::RepeatedPtrField< ::Delivered >&
UACommands::finish() const {
  // @@protoc_insertion_point(field_list:UACommands.finish)
  return finish_;
}

// repeated int64 acks = 4;
inline int UACommands::acks_size() const {
  return acks_.size();
}
inline void UACommands::clear_acks() {
  acks_.Clear();
}
inline ::google::protobuf::int64 UACommands::acks(int index) const {
  // @@protoc_insertion_point(field_get:UACommands.acks)
  return acks_.Get(index);
}
inline void UACommands::set_acks(int index, ::google::protobuf::int64 value) {
  acks_.Set(index, value);
  // @@protoc_insertion_point(field_set:UACommands.acks)
}
inline void UACommands::add_acks(::google::protobuf::int64 value) {
  acks_.Add(value);
  // @@protoc_insertion_point(field_add:UACommands.acks)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int64 >&
UACommands::acks() const {
  // @@protoc_insertion_point(field_list:UACommands.acks)
  return acks_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int64 >*
UACommands::mutable_acks() {
  // @@protoc_insertion_point(field_mutable_list:UACommands.acks)
  return &acks_;
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_amazon_5fups_2eproto__INCLUDED
